### ISSUE TITLE
Core Functionality - Step Three Issues

### ISSUE THREAD

**Issue by w-tronvig223** [Renaskigi/TheSpaceBetween#18]
Step Three Sub-Issues: 

1. Create package.json file and package-lock.json file (which is auto created). 
2. Create data entity diagram (our data table).
3. Should be something like: 

Accounts: 
Username
Password
Email

Previous Locations:
Longitude 
Latitude
Account (to link with accounts data)
Timestamp

Results (returned from google maps server)
Coffee
Restaurants
Gas
Grocery
Etc.

**Comment by Renaskigi** [comment]
All of these are done.
