### ISSUE TITLE
Steps Before Sunday

### ISSUE THREAD

**Issue by w-tronvig223** [Renaskigi/TheSpaceBetween#37]
1. Figure out how to get routes to show up on map page. This will be a function that takes the user input and displays the route. Need to use geocoding maps api to transform addresses into longitude and latitude. 

2. Figure out how to hide API key. 

3. Figure out theme. 

4. Inner page and other page navigation. Using Page.js.

**Comment by Renaskigi** [comment]
So... did anyone do any of this?
